config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :events
  resources :users, only: [:new, :show, :create]
  resources :event_attendees, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"

    has_many :event_attendees
    has_many :attendees, through: :event_attendees, source: :attendee

    validates :name, presence: true, length: {minimum: 4, maximum: 60}
    validates :location, presence: true, length: {minimum: 4, maximum: 50}
    validates :time, presence: true, uniqueness: true
    validates :description, presence: true, length: {minimum: 4, maximum: 200}

    scope :past, -> { where('time < ?', Time.now) }
    scope :upcoming, -> { where('time >= ?', Time.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, foreign_key: "creator_id", class_name: "Event"

    has_many :event_attendees, foreign_key: :attendee_id
    has_many :attended_events, through: :event_attendees, source: :event
    validates :name, presence: true, uniqueness: true, length: {minimum: 4, maximum: 14}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController

    def create
        @found_user = User.find_by(name: event_attendee_params[:attendee_id])
        if @found_user
            event_attendee_params[:attendee_id] = @found_user.id
            respond_to do |format|
                if @found_user.event_attendees.build(event_attendee_params).save
                    format.html { redirect_to event_path, notice: "User invited!" }
                    format.json { render :show, status: :created, location: @event }
                else
                    format.html { redirect_to event_path, alert: "User could not be invited" }
                    format.json { render json: @event_attendee.errors, status: :unprocessable_entity }
                end
            end
        else
            redirect_to event_path, alert: "Oops that user could not be found!"
        end
    end


    private
        # Only allow a list of trusted parameters through.
        def event_path
            Event.find(event_attendee_params[:event_id])
        end
        def event_attendee_params
            params.require(:event_attendee).permit(:attendee_id, :event_id)
        end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    find_user_session
    @event_attendee = EventAttendee.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    find_user_session
    unless @user
      redirect_to root_path
      return
    end
    @event = @user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    # Returns current user stored in session
    def find_user_session
      @user = User.find(session[:user]["id"])
    end
    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :location, :time, :description)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users/1 or /users/1.json
  def show
    set_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    if @existing_user = User.find_by(name: user_params[:name])
      session[:user] = @existing_user
      redirect_to session[:user], notice: "Welcome back"
      return
    end
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user] = @user
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendees/_create.html.erb
<%= form_for @event_attendee do |form| %>
    <%= form.hidden_field :event_id, value: @event.id %>
    <div class="field">
        <%= form.text_field :attendee_id, class:"input" %>
    </div>

    <div class="actions has-text-centered">
        <%= form.submit "Invite User", class:"button is-danger" %>
    </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:"label" %>
    <%= form.text_field :name, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :location, class:"label" %>
    <%= form.text_field :location, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :description, class:"label" %>
    <%= form.text_field :description, class:"textarea" %>
  </div>

  <div class="field">
    <%= form.label :time, class:"label" %>
    <%= form.datetime_select :time %>
  </div>

  <div class="block"></div>
  
  <div class="actions has-text-centered">
    <%= form.submit "Create Event", class:"button is-success" %>
  </div>
<% end %>

app/views/events/_invited.html.erb
<div class="block">
    <div class="panel">
        <div class="panel-heading">
            <p>Who's invited?</p>
        </div>
        <% if @event.attendees.empty? %>
            <p class="panel-block">Looks like noones invited!</p>
        <% else %>
            <% @event.attendees.each do |attendee| %>
                <%= link_to attendee.name, attendee, class:"panel-block" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="block"></div>

<div class="block level-item">
  <div class="column is-three-quarters">
    <div class="columns">
      <div class="column is-half">
        <div class="has-text-centered">
          <p class="title">All upcoming events</p>
        </div>
        <div class="block"></div>
        <% @events.upcoming.each do |event| %>
          <div class="block">
            <div class="card">
              <div class="card-content">
                <%= link_to event.name, event, class:"title"%><br>
                <p class="subtitle"><%= event.location %></p><br>
                <p><%= event.description%></p>
              </div>
              <footer class="card-footer">
                <p class="card-footer-item"><%= event.time.to_formatted_s(:long_ordinal) %></p>
                <%= link_to event.creator.name, event.creator, class:"card-footer-item"%>
              </footer>
            </div>
          </div>
        <% end %>
      </div>
      <div class="column is-half">
        <div class="has-text-centered">
          <p class="title">All past events</p>
        </div>
        <div class="block"></div>
        <% @events.past.each do |event| %>
          <div class="block">
            <div class="card">
              <div class="card-content">
                <%= link_to event.name, event, class:"title"%><br>
                <p class="subtitle"><%= event.location %></p><br>
                <p><%= event.description%></p>
              </div>
              <footer class="card-footer">
                <p class="card-footer-item"><%= event.time.to_formatted_s(:long_ordinal) %></p>
                <%= link_to event.creator.name, event.creator, class:"card-footer-item"%>
              </footer>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="block"></div>
<div class="block level-item">
    <div class="column is-half">
        <%= render 'form', event: @event %>
    </div>
</div>

app/views/events/show.html.erb
<div class="block"></div>
<div class="block level-item">
  <p class="title"><%= @event.name %></p>
</div>


<div class="block level-item">
  <div class="column is-three-quarters">
    <div class="columns">
      <div class="column is-half">
        <div class="card">
          <div class="card-content">
            <p class="subtitle"><%= @event.location %></p><br>
            <p><%= @event.description%></p>
            <% if @user == @event.creator %>
              <br>
              <div class="level-item">
                <%= render "event_attendees/create" %>
              </div>
            <% end %>
          </div>
          <footer class="card-footer">
            <p class="card-footer-item"><%= @event.time.to_formatted_s(:long_ordinal)%></p>
            <%= link_to @event.creator.name, @event.creator, class:"card-footer-item"%>
          </footer>
        </div>
      </div>
      <div class="column is-half">
        <%= render "invited" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-danger" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <%= link_to "Eventure", root_path, class:"title has-text-white is-size-2"%>
        </div>
      </div>
      <div class="navbar-menu">
        <div class="navbar-start">
          <% if session[:user] %>
            <div class="navbar-item">
            </div>
            <div class="navbar-item">
              <%= link_to session[:user]["name"], "/users/" + session[:user]["id"].to_s, class:"is-size-5 has-text-white"%>
            </div>
            <div class="navbar-item">
              <%= link_to 'New Event', new_event_path, class:"button is-info" %>
            </div>
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if session[:user] %>
              <%= link_to "Change user", new_user_path, class:"is-size-5 has-text-white"%>
            <% else %>
              <%= link_to "Log in", new_user_path, class:"is-size-5 has-text-white"%>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="notification is-info global-notification p-2">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-warning global-notification p-2">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:"label" %>
    <%= form.text_field :name, class:"input" %>
  </div>

  <div class="actions has-text-centered">
    <%= form.submit "Log In", class:"button is-success" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="block"></div>
<div class="block level-item">
    <div class="column is-half">
        <%= render 'form', user: @user %>
    </div>
</div>

app/views/users/show.html.erb
<div class="block"></div>
<div class="block level-item">
  <p class="title"><%=@user.name%>'s events</p>
</div>




<div class="block level-item">
  <div class="column is-three-quarters">
    <div class="columns">
      <div class="column is-one-third">
        <div class="panel">
          <div class="panel-heading">
            <p class="title is-4">Created Events</p>
          </div>
          <% if @user.created_events.empty?%>
            <p class="panel-block">There are no events to display!</p>
          <% else%>
            <% @user.created_events.each do |event| %>
              <%= link_to event.name, event, class:"panel-block"%>
            <% end %>
          <% end%>
        </div>
      </div>
      <div class="column is-one-third">
        <div class="panel is-info">
          <div class="panel-heading">
            <p class="title is-4 has-text-white">Upcoming Events</p>
          </div>
          <% if @user.attended_events.upcoming.empty?%>
            <p class="panel-block">There are no events to display!</p>
          <% else%>
            <% @user.attended_events.upcoming.each do |event| %>
              <%= link_to event.name, event, class:"panel-block"%>
            <% end %>
          <% end%>
        </div>
      </div>
      <div class="column is-one-third">
        <div class="panel is-danger">
          <div class="panel-heading">
            <p class="title is-4 has-text-white">Past Events</p>
          </div>
          <% if @user.attended_events.past.empty?%>
            <p class="panel-block">There are no events to display!</p>
          <% else%>
            <% @user.attended_events.past.each do |event| %>
              <%= link_to event.name, event, class:"panel-block"%>
            <% end %>
          <% end%>
        </div>
      </div>
    </div>
  </div>
</div>